### ISSUE TITLE
Loses connection to LDAP server after a while and needs to restart

### ISSUE THREAD

**Issue by ephracis** [gyselroth/kube-ldap#18]
After kube-ldap has been running for a while (a day or two I think) it starts to timeout when doing /auth.

If I delete the pod and wait for a new one to be created it works fine. Nothing shows up in the log even though I have debug enabled.

**Comment by juckerf** [comment]
which version of kube-ldap are you running?
A bug with similar symptoms was fixed in v1.2.0 (via #15, also see issue #13)

**Comment by ephracis** [comment]
I am running 1.2.1 but I had to do some minor adjustments (support ldap without tls and groups in, at least our, AD are not always lists but sometimes a single name). Other than that it is unmodified.

I have tried to tinker with the reconnect parameters but I can't make it stable over more than a couple of days.

**Comment by juckerf** [comment]
hm.. sounds strange
on the dev branch (588a90b2dd750a0ef1943b076305abd6ad415c08) I added logging to the ldap connection. probably you can merge this with your custom version and then we should at least have some debug output.

**Comment by ephracis** [comment]
I believe I have that.

```
$ $ kubectl -n kube-system get deploy kube-ldap -o yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: ... snip ...
  creationTimestamp: "2018-12-15T21:45:19Z"
  generation: 1
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    basalt.se/zone: Infra
    k8s-app: kube-ldap
    kubernetes.io/cluster-service: "true"
  name: kube-ldap
  namespace: kube-system
  resourceVersion: "493"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/kube-ldap
  uid: b79241fd-00b2-11e9-92b9-fa163ead1760
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kube-ldap
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        addonmanager.kubernetes.io/mode: Reconcile
        k8s-app: kube-ldap
    spec:
      containers:
      - env:
        - name: LDAP_URI
          value: ldap://10.0.0.10:389
        - name: LDAP_BINDDN
          valueFrom:
            secretKeyRef:
              key: binddn
              name: kube-ldap-ldap-bind-credentials
        - name: LDAP_BINDPW
          valueFrom:
            secretKeyRef:
              key: bindpw
              name: kube-ldap-ldap-bind-credentials
        - name: LDAP_BASEDN
          value: ou=users,dc=example,dc=com
        - name: LDAP_FILTER
          value: (sAMAccountName=%s)
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              key: key
              name: kube-ldap-jwt-key
        - name: JWT_TOKEN_LIFETIME
          value: "28800"
        - name: TLS_CERT_PATH
          value: /etc/ssl/kube-ldap/tls.crt
        - name: TLS_KEY_PATH
          value: /etc/ssl/kube-ldap/tls.key
        - name: MAPPING_USERNAME
          value: sAMAccountName
        - name: MAPPING_UID
          value: sAMAccountName
        - name: MAPPING_GROUPS
          value: memberOf
        - name: MAPPING_EXTRAFIELDS
        - name: LOGLEVEL
          value: debug
        - name: LDAP_TIMEOUT
          value: "60"
        - name: LDAP_RECONN_INIT_DELAY
          value: "10"
        - name: LDAP_RECONN_MAX_DELAY
          value: "60000"
        - name: LDAP_RECONN_FAIL_AFTER
          value: "1000"
        image: docker.basalt.se:5001/containers/kubernetes/kube_ldap:dev-1.2.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: kube-ldap
        ports:
        - containerPort: 8081
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ssl/kube-ldap
          name: kube-ldap-tls
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: kube-ldap-tls
        secret:
          defaultMode: 420
          secretName: kube-ldap-tls
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2018-12-15T21:45:24Z"
    lastUpdateTime: "2018-12-15T21:45:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2018-12-15T21:45:19Z"
    lastUpdateTime: "2018-12-15T21:45:24Z"
    message: ReplicaSet "kube-ldap-7dd8d9d849" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

**Comment by juckerf** [comment]
> I believe I have that.
> 
> ```
>[...]
> ```
Yep, your deployment seems OK.
Are you sure you have pulled the latest changes from the dev branch before building the image? (latest commit was 01752742e92abfa37dd62d3c2f37bb886685b796 on Nov 30th) 

If everything is correct something like the following should be logged by the pod when trying to authenticate:
```
2018-12-18T13:58:48.843Z - info: kube-ldap listening on http port 8080
2018-12-18T13:58:48.942Z - debug: connected after 1 attempt(s)
2018-12-18T13:58:49.035Z - debug: sending request {"messageID":1,"protocolOp":"ExtendedRequest","requestName":"1.3.6.1.4.1.1466.20037","requestValue":null,"controls":[]}
2018-12-18T13:58:49.038Z - debug: data event: <Buffer 30 0c 02 01 01 78 07 0a 01 00 04 00 04 00>
2018-12-18T13:58:49.040Z - debug: parse: data=<Buffer 0a 01 00 04 00 04 00>
2018-12-18T13:58:49.041Z - debug: Parsing done: {"messageID":1,"protocolOp":"ExtendedResponse","status":0,"matchedDN":"","errorMessage":"","referrals":[],"controls":[]}
2018-12-18T13:58:49.041Z - debug: response received messageID=1, protocolOp=ExtendedResponse, status=0, matchedDN=, errorMessage=, referrals=[], responseName=undefined, responseValue=undefined, controls=[]
2018-12-18T13:58:49.841Z - info: ::ffff:192.168.100.186 - - [18/Dec/2018:13:58:49 +0000] "POST /token HTTP/1.1" 200 904 "-" "Go-http-client/2.0"

2018-12-18T13:59:02.890Z - info: ::ffff:10.51.6.1 - - [18/Dec/2018:13:59:02 +0000] "GET /healthz HTTP/1.1" 200 2 "-" "kube-probe/1.8"

2018-12-18T13:59:12.449Z - info: ::ffff:10.51.6.1 - - [18/Dec/2018:13:59:12 +0000] "GET /auth HTTP/1.1" 401 12 "-" "curl/7.47.0"

2018-12-18T13:59:12.889Z - info: ::ffff:10.51.6.1 - - [18/Dec/2018:13:59:12 +0000] "GET /healthz HTTP/1.1" 200 2 "-" "kube-probe/1.8"

2018-12-18T13:59:17.824Z - debug: sending request {"messageID":2,"protocolOp":"BindRequest","version":3,"name":"uid=bind,ou=people,dc=example,dc=com","authenticationType":"Simple","credentials":"secret","controls":[]}
2018-12-18T13:59:17.825Z - debug: data event: <Buffer 30 0c 02 01 02 61 07 0a 01 00 04 00 04 00>
2018-12-18T13:59:17.826Z - debug: parse: data=<Buffer 0a 01 00 04 00 04 00>
2018-12-18T13:59:17.826Z - debug: Parsing done: {"messageID":2,"protocolOp":"LDAPResult","status":0,"matchedDN":"","errorMessage":"","referrals":[],"controls":[]}
2018-12-18T13:59:17.826Z - debug: response received messageID=2, protocolOp=LDAPResult, status=0, matchedDN=, errorMessage=, referrals=[], controls=[]
2018-12-18T13:59:17.839Z - debug: sending request {"messageID":3,"protocolOp":"SearchRequest","baseObject":{"rdns":[{"attrs":{"dc":{"value":"example","name":"dc","order":0}},"spLead":0,"spTrail":0},{"attrs":{"dc":{"value":"com","name":"dc","order":0}},"spLead":0,"spTrail":0}],"_format":{}},"scope":"sub","derefAliases":0,"sizeLimit":0,"timeLimit":10,"typesOnly":false,"filter":"(&(uid=test)(memberOf=cn=k8s,ou=groups,dc=example,dc=com))","attributes":[],"controls":[]}
2018-12-18T13:59:17.842Z - debug: data event: <Buffer 30 0c 02 01 03 65 07 0a 01 00 04 00 04 00>
2018-12-18T13:59:17.842Z - debug: parse: data=<Buffer 0a 01 00 04 00 04 00>
2018-12-18T13:59:17.842Z - debug: Parsing done: {"messageID":3,"protocolOp":"LDAPResult","status":0,"matchedDN":"","errorMessage":"","referrals":[],"controls":[]}
2018-12-18T13:59:17.842Z - debug: response received messageID=3, protocolOp=LDAPResult, status=0, matchedDN=, errorMessage=, referrals=[], controls=[]
2018-12-18T13:59:17.843Z - info: no object found with filter [(&(uid=test)(memberOf=cn=k8s,ou=groups,dc=example,dc=com))]
2018-12-18T13:59:17.844Z - info: ::ffff:10.51.6.1 - test [18/Dec/2018:13:59:17 +0000] "GET /auth HTTP/1.1" 401 12 "-" "curl/7.47.0"
```

**Comment by ephracis** [comment]
It's very weird:

```
$ kubectl -n kube-system exec kube-ldap-7dd8d9d849-cg49t -- cat /srv/www/kube-ldap/.git/refs/heads/master
dff511f246419e455fbbedc3f4a9995f7eafa98a
```

Here is my Dockerfile:

```
FROM gyselroth/kube-ldap:latest

RUN rm -rf /srv/www && \
    mkdir -p /srv/www/ && \
    apk add --no-cache git && \
    git clone https://github.com/gyselroth/kube-ldap /srv/www/kube-ldap && \
    cd /srv/www/kube-ldap && \
    git checkout dev

COPY src /srv/www/kube-ldap/src
RUN cd /srv/www/kube-ldap && \
  yarn install && \
  yarn run build && \
  yarn install --production=true

CMD ["node", "/srv/www/kube-ldap/build/index.js"]
```

The patch I am doing (when copying over src) is only to do two small adjustments: 1) allow LDAP without TLS and 2) fix an issue because our Active Directory is not returning groups as a list but as a single string.

**Comment by ephracis** [comment]
I just tried again and here are the logs for it:

```
2018-12-29T10:33:36.187Z - debug: Setting timeout to 60000
2018-12-29T10:33:36.189Z - debug: sending request {"messageID":1,"protocolOp":"BindRequest","version":3,"name":"administrator@example.com","authenticationType":"Simple","credentials":"redacted","controls":[]}
2018-12-29T10:34:36.197Z - debug: response received msg=undefined
2018-12-29T10:34:36.200Z - debug: Setting timeout to 60000
2018-12-29T10:34:36.201Z - debug: sending request {"messageID":2,"protocolOp":"SearchRequest","baseObject":{"rdns":[{"attrs":{"ou":{"value":"users","name":"ou","order":0}},"spLead":0,"spTrail":0},{"attrs":{"ou":{"value":"Example","name":"OU","order":0}},"spLead":0,"spTrail":0},{"attrs":{"dc":{"value":"example","name":"dc","order":0}},"spLead":0,"spTrail":0},{"attrs":{"dc":{"value":"com","name":"dc","order":0}},"spLead":0,"spTrail":0}],"_format":{}},"scope":"sub","derefAliases":0,"sizeLimit":0,"timeLimit":10,"typesOnly":false,"filter":"(sAMAccountName=test.user00001)","attributes":[],"controls":[]}
2018-12-29T10:34:36.202Z - info: request timeout (client interrupt)
2018-12-29T10:34:36.207Z - info: ::ffff:172.16.66.1 - test.user00001 [29/Dec/2018:10:34:36 +0000] "GET /auth HTTP/1.1" 401 12 "-" "curl/7.29.0"
2018-12-29T10:34:38.916Z - info: Error while verifying token: [JsonWebTokenError] with message [jwt malformed]
2018-12-29T10:34:38.918Z - info: ::ffff:172.16.96.0 - - [29/Dec/2018:10:34:38 +0000] "POST /token?timeout=30s HTTP/1.1" 200 100 "-" "Go-http-client/1.1"
2018-12-29T10:34:39.260Z - info: Error while verifying token: [JsonWebTokenError] with message [jwt malformed]
2018-12-29T10:34:39.262Z - info: ::ffff:172.16.96.0 - - [29/Dec/2018:10:34:39 +0000] "POST /token?timeout=30s HTTP/1.1" 200 100 "-" "Go-http-client/1.1"
2018-12-29T10:35:36.200Z - debug: response received msg=undefined
```

**Comment by ephracis** [comment]
If I kill the pod and have Kubernetes recreated it, then it starts working again (for a day or two). The LDAP server is a vanilla Active Directory on Windows Server 2016 with minimal configuration.

But it contains a very large directory with over 5k users inside the group.

**Comment by juckerf** [comment]
Hmm.. the ldap library should reconnect to the server, but someone mentioned that this might not work very well with active directory (https://github.com/joyent/node-ldapjs/issues/498#issuecomment-445245002). I'm going to have a look into this (probably recreate the ldap connection for every request)

**Comment by var-kar** [comment]
@juckerf In our company we have similar applications written on Spring framework. We use this class https://docs.spring.io/spring-ldap/docs/current/apidocs/org/springframework/ldap/core/support/LdapContextSource.html

The Java applications that our team wrote with this class are working well with the same LDAP source with similar connection details.

**Comment by juckerf** [comment]
@ephracis 
I made some improvements and tested reconnection with Active Directory (provoking a connection loss by restarting the AD service), however I'm not sure if this will really apply to your case.
I released the changes with version 1.3.0 of kube-ldap. This version also includes a new configuration parameter to disable ldap starttls (LDAP_STARTTLS) so you probably don't have to build your own image anymore.

@var-kar 
Thanks for your input. However I'm not sure what you're trying to say. Can you please be more specific what this java class has to do with kube-ldap?

**Comment by var-kar** [comment]
@juckerf https://github.com/joyent/node-ldapjs/issues/498
Earlier you linked the above issue with this one. 

Any solution on the core ldapjs library to this connection issue?

Thank you.

**Comment by ephracis** [comment]
Been running the 1.3.0 for 2 days now and still not seeing any issue. I will let it run for a few more days but it usually shows up within 3 days, most often after only 1 day. Never seen it go for more than 3 days without an issue.

So I am optimistic that 1.3.0 solves the issue. But I'll keep this issue open for a few more days until I am certain that it's solved.

**Comment by ephracis** [comment]
The problem is back.

So in the logs I usually see this every 3 minutes:

```
2019-01-10T21:05:12.435Z - debug: error event: Error
    at Socket.onSocketError (/srv/www/kube-ldap/node_modules/ldapjs/lib/client/client.js:1167:50)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9) errno=ECONNRESET, code=ECONNRESET, syscall=read
2019-01-10T21:05:12.436Z - error: uncaughtException: read ECONNRESET date=Thu Jan 10 2019 21:05:12 GMT+0000 (UTC), pid=1, uid=0, gid=0, cwd=/, execPath=/usr/local/bin/node, version=v8.15.0, argv=[/usr/local/bin/node, /srv/www/kube-ldap/build/index.js], rss=54902784, heapTotal=26034176, heapUsed=19457784, external=74980, loadavg=[0.0078125, 0.041015625, 0.09716796875], uptime=203986, trace=[column=25, file=net.js, function=TCP.onread, line=622, method=onread, native=false], stack=[Error: read ECONNRESET,     at TCP.onread (net.js:622:25)]
2019-01-10T21:05:12.437Z - debug: close event had_err=yes
2019-01-10T21:05:12.542Z - debug: connected after 1 attempt(s)
```

But then last night that stopped and now when I try to access `/auth` I get this:

```
2019-01-11T07:40:51.922Z - debug: sending request {"messageID":1,"protocolOp":"BindRequest","version":3,"name":"administrator@example.com","authenticationType":"Simple","credentials":"redacted","controls":[]}
2019-01-11T07:42:51.752Z - info: ::ffff:172.16.12.1 - test.user00001 [11/Jan/2019:07:42:51 +0000] "GET /auth HTTP/1.1" - - "-" "curl/7.29.0"
2019-01-11T07:42:54.486Z - info: Error while verifying token: [JsonWebTokenError] with message [jwt malformed]
2019-01-11T07:42:54.487Z - info: ::ffff:172.16.73.0 - - [11/Jan/2019:07:42:54 +0000] "POST /token?timeout=30s HTTP/1.1" 200 100 "-" "Go-http-client/1.1"
```

**Comment by ephracis** [comment]
Don't think we have changed anything.

```
Policy                          Current(New)

MaxPoolThreads                  4
MaxPercentDirSyncRequests                       0
MaxDatagramRecv                 4096
MaxReceiveBuffer                        10485760
InitRecvTimeout                 120
MaxConnections                  5000
MaxConnIdleTime                 900
MaxPageSize                     1000
MaxBatchReturnMessages                  0
MaxQueryDuration                        120
MaxDirSyncDuration                      0
MaxTempTableSize                        10000
MaxResultSetSize                        262144
MinResultSets                   0
MaxResultSetsPerConn                    0
MaxNotificationPerConn                  5
MaxValRange                     1500
MaxValRangeTransitive                   0
ThreadMemoryLimit                       0
SystemMemoryLimitPercent                        0
```

**Comment by ephracis** [comment]
Seems like the best option is to switch from ldapjs to https://github.com/ldapts/ldapts since that one is better maintained.

How big of an undertaking would that be? Any plans on doing such a switch?

**Comment by juckerf** [comment]
> Seems like the best option is to switch from ldapjs to https://github.com/ldapts/ldapts since that one is better maintained.
> 
> How big of an undertaking would that be? Any plans on doing such a switch?

I was already thinking about switching to ldapts, too. I was hoping that ldapjs maintenance gets picked up by someone, but the longer I think about I guess that we've no choice than to switch to ldapts. It shouldn't be a lot of work, but I'm very busy at the moment so it could take another couple weeks...

**Comment by juckerf** [comment]
@ephracis I finally found the time to switch to ldapts. 
The changes are available on the dev-branch and the dev-docker image tag.

**Comment by juckerf** [comment]
There was a bug in v2.0.0 which lead to very similar symptoms. The bug has been identified and fixed in v2.0.1. Chances are that this problem is also resolved now.

**Comment by jeinwag** [comment]
@juckerf Looks like I'm experiencing the same issue. I'm currently running 2.0.1. Authentication works fine, but after a while, the pod becomes unresponsive and gets restarted until it goes into a CrashLoopBackOff-state.
I already set LOGLEVEL to debug, but it doesn't show any more information in the logs than with the default setting.

**Comment by jeinwag** [comment]
@juckerf never mind, it was a misconfiguration in my part. The schema and port of the liveness probe had to be adjusted.
